import { PlaceHolderImages } from './placeholder-images';

const findImage = (id: string) => PlaceHolderImages.find(img => img.id === id)?.imageUrl || '';

export const users = [
    { id: 'u1', name: 'Alex Johnson', college: 'Stanford University', avatarUrl: findImage('user1') },
    { id: 'u2', name: 'Maria Garcia', college: 'UC Berkeley', avatarUrl: findImage('user2') },
    { id: 'u3', name: 'Chen Wei', college: 'MIT', avatarUrl: findImage('user3') },
    { id: 'u4', name: 'Fatima Al-Fassi', college: 'Harvard University', avatarUrl: findImage('user4') }
];

export const colleges = [
    { id: '1', name: "Ajeenkya DY Patil University, Pune"},
    { id: '2', name: "Annasaheb Dange College of Engineering and Technology, Ashta"},
    { id: '3', name: "Army Institute of Technology (AIT), Pune"},
    { id: '4', name: "Atharva College of Engineering, Mumbai"},
    { id: '5', name: "Bharati Vidyapeeth (Deemed University) College of Engineering, Pune"},
    { id: '6', name: "College of Engineering Pune (COEP) Technological University, Pune"},
    { id: '7', name: "Columbia University"},
    { id: '8', name: "Cummins College of Engineering for Women, Pune"},
    { id: '9', name: "DKTE Society's Textile and Engineering Institute, Ichalkaranji"},
    { id: '10', name: "Datta Meghe College of Engineering, Navi Mumbai"},
    { id: '11', name: "Defence Institute of Advanced Technology (DIAT), Pune"},
    { id: '12', name: "Deogiri Institute of Engineering and Management Studies, Aurangabad"},
    { id: '13', name: "Don Bosco Institute of Technology (DBIT), Mumbai"},
    { id: '14', name: "Dr. B. R. Ambedkar National Institute of Technology Jalandhar - NITJ"},
    { id: '15', name: "Dr. D.Y. Patil Institute of Technology, Pimpri, Pune"},
    { id: '16', name: "Dwarkadas J. Sanghvi College of Engineering (DJSCE), Mumbai"},
    { id: '17', name: "Fr. Conceicao Rodrigues College of Engineering (CRCE), Bandra, Mumbai"},
    { id: '18', name: "G.H. Raisoni College of Engineering, Nagpur"},
    { id: '19', name: "Government College of Engineering and Research, Avasari"},
    { id: '20', name: "Government College of Engineering, Amravati"},
    { id: '21', name: "Government College of Engineering, Aurangabad (Chhatrapati Sambhajinagar)"},
    { id: '22', name: "Government College of Engineering, Karad"},
    { id: '23', name: "Harvard University"},
    { id: '24', name: "Indian Institute of Technology (BHU) Varanasi - IIT(BHU)"},
    { id: '25', name: "Indian Institute of Technology (IIT) Bombay, Mumbai"},
    { id: '26', name: "Indian Institute of Technology Bhubaneswar - IITBBS"},
    { id: '27', name: "Indian Institute of Technology Bombay - IITB"},
    { id: '28', name: "Indian Institute of Technology Delhi - IITD"},
    { id: '29', name: "Indian Institute of Technology Gandhinagar - IITGN"},
    { id: '30', name: "Indian Institute of Technology Guwahati - IITG"},
    { id: '31', name: "Indian Institute of Technology Hyderabad - IITH"},
    { id: '32', name: "Indian Institute of Technology Indore - IITI"},
    { id: '33', name: "Indian Institute of Technology Jodhpur - IITJ"},
    { id: '34', name: "Indian Institute of Technology Kanpur - IITK"},
    { id: '35', name: "Indian Institute of Technology Kharagpur - IITKGP"},
    { id: '36', name: "Indian Institute of Technology Madras - IITM"},
    { id: '37', name: "Indian Institute of Technology Mandi - IIT Mandi"},
    { id: '38', name: "Indian Institute of Technology Palakkad - IITPKD"},
    { id: '39', name: "Indian Institute of Technology Patna - IITP"},
    { id: '40', name: "Indian Institute of Technology Roorkee - IITR"},
    { id: '41', name: "Indian Institute of Technology Ropar - IITRPR"},
    { id: '42', name: "Indian Institute of Technology Tirupati - IITTP"},
    { id: '43', name: "Institute of Chemical Technology (ICT), Mumbai"},
    { id: '44', name: "JSPM’s Rajarshi Shahu College of Engineering, Pune"},
    { id: '45', name: "K J Somaiya College of Engineering, Mumbai"},
    { id: '46', name: "K.K. Wagh Institute of Engineering Education and Research, Nashik"},
    { id: '47', name: "Kolhapur Institute of Technology’s (KIT) College of Engg, Kolhapur"},
    { id: '48', name: "MIT"},
    { id: '49', name: "MIT World Peace University (MIT-WPU), Pune"},
    { id: '50', name: "Malaviya National Institute of Technology Jaipur - MNIT"},
    { id: '51', name: "Maulana Azad National Institute of Technology Bhopal - MANIT"},
    { id: '52', name: "Motilal Nehru National Institute of Technology Allahabad - MNNIT"},
    { id: '53', name: "National Institute of Technology Agartala - NITA"},
    { id: '54', name: "National Institute of Technology Andhra Pradesh - NITANP"},
    { id: '55', name: "National Institute of Technology Arunachal Pradesh - NITAP"},
    { id: '56', name: "National Institute of Technology Calicut - NITC"},
    { id: '57', name: "National Institute of Technology Delhi - NITD"},
    { id: '58', name: "National Institute of Technology Durgapur - NITDGP"},
    { id: '59', name: "National Institute of Technology Goa - NITG"},
    { id: '60', name: "National Institute of Technology Hamirpur - NITH"},
    { id: '61', name: "National Institute of Technology Jamshedpur - NITJSR"},
    { id: '62', name: "National Institute of Technology Kurukshetra - NITKKR"},
    { id: '63', name: "National Institute of Technology Manipur - NITMN"},
    { id: '64', name: "National Institute of Technology Meghalaya - NITM"},
    { id: '65', name: "National Institute of Technology Mizoram - NITMZ"},
    { id: '66', name: "National Institute of Technology Nagaland - NITN"},
    { id: '67', name: "National Institute of Technology Patna - NITP"},
    { id: '68', name: "National Institute of Technology Puducherry - NITPY"},
    { id: '69', name: "National Institute of Technology Raipur - NITRR"},
    { id: '70', name: "National Institute of Technology Rourkela - NITRKL"},
    { id: '71', name: "National Institute of Technology Sikkim - NITSKM"},
    { id: '72', name: "National Institute of Technology Silchar - NITS"},
    { id: '73', name: "National Institute of Technology Srinagar - NITSRI"},
    { id: '74', name: "National Institute of Technology Karnataka Surathkal - NITK"},
    { id: '75', name: "National Institute of Technology Tiruchirappalli - NITT"},
    { id: '76', name: "National Institute of Technology Uttarakhand - NITUK"},
    { id: '77', name: "National Institute of Technology Warangal - NITW"},
    { id: '78', name: "Pimpri Chinchwad College of Engineering (PCCOE), Pune"},
    { id: '79', name: "Princeton University"},
    { id: '80', name: "Prof. Ram Meghe Institute of Technology and Research, Amravati"},
    { id: '81', name: "Pune Institute of Computer Technology (PICT), Pune"},
    { id: '82', name: "Rajarshi Shahu College of Engineering, Pune"},
    { id: '83', name: "Ramdeobaba University (formerly RCOEM), Nagpur"},
    { id: '84', name: "S.B. Jain Institute of Technology, Nagpur"},
    { id: '85', name: "SIES Graduate School of Technology, Mumbai"},
    { id: '86', name: "Sandip University, Nashik"},
    { id: '87', name: "Sanjivani College of Engineering, Kopargaon"},
    { id: '88', name: "Sardar Patel Institute of Technology (SPIT), Mumbai"},
    { id: '89', name: "Sardar Vallabhbhai National Institute of Technology Surat - SVNIT"},
    { id: '90', name: "Shri Guru Gobind Singhji Institute of Engg (SGGSIE&T), Nanded"},
    { id: '91', name: "Stanford University"},
    { id: '92', name: "Symbiosis Institute of Technology (SIT), Pune"},
    { id: '93', name: "Terna Engineering College, Navi Mumbai"},
    { id: '94', name: "Thadomal Shahani Engineering College (TSEC), Mumbai"},
    { id: '95', name: "Thakur College of Engineering and Technology (TCET), Mumbai"},
    { id: '96', name: "UC Berkeley"},
    { id: '97', name: "Veermata Jijabai Technological Institute (VJTI), Mumbai"},
    { id: '98', name: "Vidyalankar Institute of Technology, Mumbai"},
    { id: '99', name: "Vishwakarma Institute of Information Technology (VIIT), Pune"},
    { id: '100', name: "Vishwakarma Institute of Technology (VIT), Pune"},
    { id: '101', name: "Visvesvaraya National Institute of Technology (VNIT), Nagpur"},
    { id: '102', name: "Vivekanand Education Society's Institute of Technology (VESIT), Mumbai"},
    { id: '103', name: "Walchand College of Engineering, Sangli"},
    { id: '104', name: "Yeshwantrao Chavan College of Engineering (YCCE), Nagpur"},
    { id: '105', name: "College of Engineering Pune - COEP"},
    { id: '106', name: "Veermata Jijabai Technological Institute Mumbai - VJTI"},
    { id: '107', name: "Institute of Chemical Technology Mumbai - ICT"},
    { id: '108', name: "Walchand College of Engineering Sangli - WCE"},
    { id: '109', name: "Government College of Engineering Pune - GCOE"},
    { id: '110', name: "Shri Guru Gobind Singhji Institute of Engineering and Technology Nanded - SGGSIET"},
    { id: '111', name: "Dr. Babasaheb Ambedkar Technological University Lonere - DBATU"},
    { id: '112', name: "Government College of Engineering Aurangabad - GCOEA"},
    { id: '113', name: "Government College of Engineering Amravati - GCOEA"},
    { id: '114', name: "Government College of Engineering Karad - GCEK"},
    { id: '115', name: "Government College of Engineering Nagpur - GCOEN"},
    { id: '116', name: "Ramrao Adik Institute of Technology Navi Mumbai - RAIT"},
    { id: '117', name: "Fr. Conceicao Rodrigues College of Engineering Mumbai - CRCE"},
    { id: '118', name: "K. J. Somaiya College of Engineering Mumbai - KJSCE"},
    { id: '119', name: "Dwarkadas J. Sanghvi College of Engineering Mumbai - DJSCE"},
    { id: '120', name: "Shree L. R. Tiwari College of Engineering Mumbai - SLRTCE"},
    { id: '121', name: "Pillai College of Engineering New Panvel - PCE"},
    { id: '122', name: "Pune Institute of Computer Technology Pune - PICT"},
    { id: '123', name: "Maharashtra Institute of Technology Pune - MIT"},
    { id: '124', name: "Cummins College of Engineering Pune - CCOE"},
    { id: '125', name: "Sinhgad College of Engineering Pune - SCOE"},
    { id: '126', name: "Pimpri Chinchwad College of Engineering Pune - PCCOE"},
    { id: '127', name: "Army Institute of Technology Pune - AIT"},
    { id: '128', name: "D. Y. Patil College of Engineering Pune - DYP"},
    { id: '129', name: "Bharati Vidyapeeth College of Engineering Pune - BVCOE"},
    { id: '130', name: "AISSMS College of Engineering Pune - AISSMSCOE"},
    { id: '131', name: "Rajarshi Shahu College of Engineering Pune - RSCOE"},
    { id: '132', name: "NBN Sinhgad School of Engineering Pune - NBNSSOE"},
    { id: '133', name: "Zeal College of Engineering and Research Pune - ZCOER"},
    { id: '134', name: "Government College of Engineering Jalgaon - GCOEJ"},
    { id: '135', name: "Government College of Engineering Chandrapur - GCOEC"},
    { id: '136', name: "K. D. K. College of Engineering Nagpur - KDKCE"},
    { id: '137', name: "Priyadarshini College of Engineering Nagpur - PCE"},
    { id: '138', name: "Shri Ramdeobaba College of Engineering Nagpur - RCOEM"},
    { id: '139', name: "Government College of Engineering Osmanabad - GCOEO"},
    { id: '140', name: "Smt. Kashibai Navale College of Engineering Pune - SKNCOE"},
    { id: '141', name: "Jayawantrao Sawant College of Engineering Pune - JSCOE"},
    { id: '142', name: "Marathwada Institute of Technology Aurangabad - MIT"},
    { id: '143', name: "MGM's College of Engineering Navi Mumbai - MGMCOE"},
    { id: '144', name: "Rajiv Gandhi Institute of Technology Mumbai - RGIT"},
    { id: '145', name: "Shah and Anchor Kutchhi Engineering College Mumbai - SAKEC"},
    { id: '146', name: "Lokmanya Tilak College of Engineering Navi Mumbai - LTCE"},
    { id: '147', name: "Terna Engineering College Navi Mumbai - TEC"},
    { id: '148', name: "Indira College of Engineering and Management Pune - ICOEM"},
    { id: '149', name: "Vellore Institute of Technology Tamil Nadu - VIT"},
    { id: '150', name: "Birla Institute of Technology and Science Pilani Rajasthan - BITS Pilani"},
    { id: '151', name: "Jadavpur University West Bengal - JU"},
    { id: '152', name: "SRM Institute of Science and Technology Tamil Nadu - SRMIST"},
    { id: '153', name: "Anna University Tamil Nadu - AU"},
    { id: '154', name: "Amrita Vishwa Vidyapeetham Tamil Nadu - AVV"},
    { id: '155', name: "Jamia Millia Islamia New Delhi - JMI"},
    { id: '156', name: "Siksha O Anusandhan Odisha - SOA"},
    { id: '157', name: "Delhi Technological University New Delhi - DTU"},
    { id: '158', name: "Thapar Institute of Engineering and Technology Punjab - TIET"},
    { id: '159', name: "Amity University Uttar Pradesh - AMITY"},
    { id: '160', name: "Chandigarh University Punjab - CU"},
    { id: '161', name: "Aligarh Muslim University Uttar Pradesh - AMU"},
    { id: '162', name: "Koneru Lakshmaiah Education Foundation Andhra Pradesh - KLEF"},
    { id: '163', name: "Kalasalingam Academy of Research and Education Tamil Nadu - KARE"},
    { id: '164', name: "Kalinga Institute of Industrial Technology Odisha - KIIT"},
    { id: '165', name: "Shanmugha Arts Science Technology and Research Academy Tamil Nadu - SASTRA"},
    { id: '166', name: "Sri Sivasubramaniya Nadar College of Engineering Tamil Nadu - SSNCE"},
    { id: '167', name: "Indian Institute of Engineering Science and Technology Shibpur West Bengal - IIEST"},
    { id: '168', name: "Indian Institute of Space Science and Technology Kerala - IIST"},
    { id: '169', name: "Vellore Institute of Technology Vellore Tamil Nadu - VIT Vellore"},
    { id: '170', name: "Vellore Institute of Technology Chennai Tamil Nadu - VIT Chennai"},
    { id: '171', name: "Vellore Institute of Technology Amaravati Andhra Pradesh - VIT-AP"},
    { id: '172', name: "Vellore Institute of Technology Bhopal Madhya Pradesh - VIT Bhopal"},
    { id: '173', name: "Birla Institute of Technology and Science Goa Campus - BITS Goa"},
    { id: '174', name: "Birla Institute of Technology and Science Hyderabad Campus - BITS Hyderabad"},
    { id: '175', name: "Birla Institute of Technology Mesra Jharkhand - BIT Mesra"},
    { id: '176', name: "Manipal Institute of Technology Karnataka - MIT Manipal"},
    { id: '177', name: "PSG College of Technology Tamil Nadu - PSG Tech"},
    { id: '178', name: "International Institute of Information Technology Bangalore - IIIT-B"},
    { id: '179', name: "International Institute of Information Technology Hyderabad - IIIT-H"},
    { id: '180', name: "Lovely Professional University Punjab - LPU"},
    { id: '181', name: "Saveetha Institute of Medical and Technical Sciences Tamil Nadu - SIMATS"},
    { id: '182', name: "Sathyabama Institute of Science and Technology Tamil Nadu - SIST"},
    { id: '183', name: "Sri Krishna College of Engineering and Technology Tamil Nadu - SKCET"},
    { id: '184', name: "Visvesvaraya Technological University Karnataka - VTU"},
    { id: '185', name: "M. S. Ramaiah Institute of Technology Karnataka - MSRIT"},
    { id: '186', name: "Defence Institute of Advanced Technology Maharashtra - DIAT"},
    { id: '187', name: "Rajiv Gandhi Institute of Petroleum Technology Uttar Pradesh - RGIPT"},
    { id: '188', name: "Banasthali Vidyapith Rajasthan - BV"},
    { id: '189', name: "UPES Uttarakhand - UPES"},
    { id: '190', name: "Chitkara University Punjab - CU"},
    { id: '191', name: "Graphic Era University Uttarakhand - GEU"},
    { id: '192', name: "Manipal University Jaipur Rajasthan - MUJ"},
    { id: '193', name: "C. V. Raman Global University Odisha - CVRGU"},
    { id: '194', name: "Indian Institute of Science Bangalore - IISc Bangalore"},
    { id: '195', name: "Indian Institute of Space Science and Technology Thiruvananthapuram - IIST"},
    { id: '196', name: "Indian Institute of Petroleum and Energy Visakhapatnam - IIPE"},
    { id: '197', name: "Indian Institute of Science Education and Research Pune - IISER Pune"},
    { id: '198', name: "Indian Institute of Science Education and Research Kolkata - IISER Kolkata"},
    { id: '199', name: "Indian Institute of Science Education and Research Bhopal - IISER Bhopal"},
    { id: '200', name: "Indian Institute of Science Education and Research Thiruvananthapuram - IISER TVM"},
    { id: '201', name: "Indian Institute of Science Education and Research Mohali - IISER Mohali"},
    { id: '202', name: "Indian Institute of Science Education and Research Berhampur - IISER Berhampur"},
    { id: '203', name: "Indian Institute of Science Education and Research Tirupati - IISER Tirupati"},
    { id: '204', name: "Indian Statistical Institute Kolkata - ISI Kolkata"}
];

export const buySellItems = [
  { id: 'bs1', name: 'Used MacBook Pro', description: '2019 model, 16GB RAM, 512GB SSD. Good condition, some minor scratches.', price: 65000, imageUrl: findImage('laptop1'), sellerId: 'u2', college: 'UC Berkeley' },
  { id: 'bs2', name: 'Psychology 101 Textbook', description: 'Introduction to Psychology, 15th Edition. Like new, no markings.', price: 3500, imageUrl: findImage('books1'), sellerId: 'u1', college: 'Stanford University' },
];

export const borrowLendItems = [
  { id: 'bl1', name: 'Acoustic Guitar', description: 'Yamaha F310, great for beginners. Comes with a soft case.', rate: '₹400/day', imageUrl: findImage('guitar1'), lenderId: 'u3', college: 'MIT' },
  { id: 'bl2', name: 'Canon DSLR Camera', description: 'Canon EOS Rebel T7 with 18-55mm lens. Perfect for photography projects.', rate: '₹1200/day', imageUrl: findImage('camera1'), lenderId: 'u4', college: 'Harvard University' },
];

export const lostFoundItems = [
  { id: 'lf1', name: 'Lost Keys', description: 'Set of three keys on a red lanyard. Last seen near the library.', status: 'lost', imageUrl: findImage('keys1'), posterId: 'u1', location: 'Library Lawn', college: 'Stanford University' },
  { id: 'lf2', name: 'Found Wallet', description: 'Brown leather wallet with a student ID for "Maria G." Found on a bench.', status: 'found', imageUrl: findImage('wallet1'), posterId: 'u3', location: 'Main Quad', college: 'MIT' },
  { id: 'lf3', name: 'Found Headphones', description: 'Black Sony wireless headphones in a case.', status: 'found', imageUrl: findImage('headphone1'), posterId: 'u2', location: 'Cafeteria', college: 'UC Berkeley' },
  { id: 'lf4', name: 'Lost Backpack', description: 'Gray backpack with a laptop and textbooks inside. Very important!', status: 'lost', imageUrl: findImage('backpack1'), posterId: 'u4', location: 'Engineering Building', college: 'Harvard University' },
];

export const getChatPartner = (partnerId: string) => {
    return users.find(user => user.id === partnerId);
}

export const messages: Record<string, { from: string; text: string; time: string; }[]> = {
    'bs1': [
        { from: 'u2', text: 'Hi, is this still available?', time: '10:30 AM' },
        { from: 'me', text: 'Yes, it is!', time: '10:31 AM' },
    ],
    'bs2': [],
    'bl1': [],
    'bl2': [],
    'lf1': [],
    'lf2': [],
};

export type BuySellItem = (typeof buySellItems)[0];
export type BorrowLendItem = (typeof borrowLendItems)[0];
export type LostFoundItem = (typeof lostFoundItems)[0];
